### ISSUE TITLE
issue-03 Create a landing page

### ISSUE THREAD

**Issue by JennieCab** [Clubs-At-Manoa/clubs-at-manoa.github.io#3]

**Comment by cleoso** [comment]
Requirements:
Navbar
-Clubs-At-Manoa (Header title)
-Overall list of clubs/organizations at Manoa page (button/link)
-Log in or sign up dropdown menu (dropdown)

Center page
-Background Image (Image)
-Description of what C.A.M is, what information this website offers  (Header, sub-header)

Footer
-Miscellaneous links/contact support link (button/link)

Landing page for all types of users, general description of the purpose to the website. Browse clubs without having a profile/signing in.
