### ISSUE TITLE
Project Home page - link to the Github organization

### ISSUE THREAD

**Issue by CandaceHuynh** [Clubs-At-Manoa/clubs-at-manoa.github.io#8]
To provide infrastructure for your final project development, your team should create a [GitHub Organization](https://help.github.com/articles/creating-a-new-organization-account/).

First, your team should come up with a name for your organization. It can’t be any of the names already specified in the Final Project page (i.e. “Campus Jams”, “Club Hub”, etc.) Be sure it’s a name that you wouldn’t mind future employers seeing.

Second, one member of your team should create the organization, and invite all of the other team members as owners. Create the organization in all lower case.

Third, create the home page for this organization. Let’s say you’ve named your organization “manoa-music”. Your home page needs to be at https://manoa-music.github.io.

To do this, you’ll need to create a repo within the manoa-music organization called “manoa-music.github.io”, and then create an index.md file within it with the contents of your home page in markdown format. For example, see the [bowfolios.github.io repository](https://github.com/bowfolios/bowfolios.github.io).

To learn about making GitHub pages, see [GitHub Pages Basics](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site). You need to [configure a publishing source](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/), which in this case will be the main branch of your organization’s .github.io repository. In the settings page of this repo, you’ll set the source for your page as the main branch, and select a theme using the [Jekyll Theme Chooser](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll).

In the case of the hypothetical manoa-music organization, when you are done with creating the home page, it should be accessible at https://manoa-music.github.io.

The home page for your organization should evolve over time to reflect the most recent state of your project. To begin with, the home page should provide a good description of the goals of the project, what the system should eventually provide, and screen shots of the mockup pages you plan to use as a basis for your final project.

For more guidelines, see [GitHub Hosting Guidelines](https://courses.ics.hawaii.edu/ics314s24/morea/project-management/reading-guidelines-github-hosting.html).

**Comment by JennieCab** [comment]
Estimated hours worked 2 hours
https://clubs-at-manoa.github.io/
