### ISSUE TITLE
Team Contract

### ISSUE THREAD

**Issue by CandaceHuynh** [Clubs-At-Manoa/clubs-at-manoa.github.io#9]
To work together effectively as a team, you need to know at least a little bit about each other. For this assignment, please meet (face-to-face or virtually over Discord) with your team mates. For each team member, you want to learn at least the following:

What do you want to get out of this final project (besides the obvious, which is a good grade for the course)? Are there any skills you want to practice or improve at through this project experience?
What is your background? What skills can you bring to the final project?
What are your time constraints? When are you available to meet? When do you plan to be able to work on the project?
How do you prefer to be contacted? Email? Text? Discord? When do you want to be contacted? When do you not want to be contacted?
In addition, please use this meeting time to develop your “Team Contract”. The Team Contract is a Google Doc that covers (at a minimum) the following material:

Team Membership. Who are the team members that have agreed to this contract?
Contribution Criteria. What criteria will you use to decide if a member has contributed effectively? Examples can include: level of professionalism, leadership, timeliness of attending meetings and submitted work, and willingness to collaborate.
Behavioral Criteria. What criteria will you use to decide if a member has behaved appropriately? Examples include providing feedback without criticizing, being on time and prepared, honoring the terms of this contract, and listening to each other.
Managing conflict. How will the team manage conflict or disagreement?
Failure to honor the contract. What will happen if someone fails to honor the terms of this agreement?
Signatures. The document should conclude with the “signatures” of each team member. You can provide signatures any way you want, but you cannot “sign” for someone else.
Provide a link to the Team Contract Google Doc in your project home page. Make sure the Google Doc is publicly accessible with read access.

**Comment by JennieCab** [comment]
Estimated hours worked 1 hr
https://docs.google.com/document/d/12P4cILMMUF1ZTil_tapX8uh4npj-fnaBoBRHeb4GNOQ/edit?usp=sharing

**Comment by JennieCab** [comment]
https://docs.google.com/document/d/12P4cILMMUF1ZTil_tapX8uh4npj-fnaBoBRHeb4GNOQ/edit?usp=sharing
